
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brdizsjlbqumtdepqgaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZGl6c2psYnF1bXRkZXBxZ2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzk3NTQsImV4cCI6MjA2MTgxNTc1NH0.wgH07F9a4li4-9jeX_Q6-cufnOa-ERCWcnsOQrHqEYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
